# ---------------------------------------------------------------------------------------------
# MIT License
# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke (ricardo.gomez-ulmke@solace.com)
# ---------------------------------------------------------------------------------------------

---
- hosts: sdkperf_latency
  vars_files: 
    - "./vars/bootstrap.vars.yml"
    - "./vars/sdkperf.vars.yml"
  
  tasks:
     
    - name: remove all sdkperf tasks
      become: true
      command: pkill --signal 2 -f sdkperf
      ignore_errors: true

    - pause: 
        seconds: 3
        prompt: "Waiting 3 seconds ...."
      
    - name: run sdkperf latency test
      shell: nohup taskset -c 1,2 {{sdkperf_nodes.sdkperf_root}}/sdkperf-c-x64/sdkperf_c -cip="{{ sdkperf.broker_uri }}":"{{ sdkperf.broker_port }}" -cu="{{ sdkperf.client_publisher_username }}"@"{{ sdkperf.broker_msg_vpn }}" -cp="{{ sdkperf.client_publisher_password }}" -ptl="{{ sdkperf.topics_latency }}" -stl="{{ sdkperf.topics_latency }}" -mn="{{ sdkperf.latency_msg_number }}" -msa="{{ sdkperf.latency_msg_payload_size_bytes }}" -mr="{{ sdkperf.latency_msg_rate_per_second }}" -psm -lat -lwu=10 -lb=4096 -lg=15 -l </dev/null > {{sdkperf_nodes.sdkperf_log_root}}/{{sdkperf.datetimeprefix}}-{{sdkperf.latency_log_filename}}-1.log 2>&1 &

    
  