# ---------------------------------------------------------------------------------------------
# MIT License
# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke (ricardo.gomez-ulmke@solace.com)
# ---------------------------------------------------------------------------------------------

---
- hosts: sdkperf_latency
  vars_files: 
    - "./vars/bootstrap.vars.yml"
    - "./vars/sdkperf.vars.yml"
  
  tasks:
     
    - name: kicking of playbook
      debug:
        msg: "kicking of playbook"

    - name: Invoking repeating tasks
      include_tasks: ./tasks/sdkperf.latency.testrun.yml
      with_sequence: "end={{sdkperf.latency_repeat_total_test_runs}} start=0"
     


 