# ---------------------------------------------------------------------------------------------
# MIT License
# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke (ricardo.gomez-ulmke@solace.com)
# ---------------------------------------------------------------------------------------------

---
- hosts: sdkperf_consumers
  vars_files:
    - "./vars/bootstrap.vars.yml"
    - "./vars/sdkperf.vars.yml"

  tasks:
    - name: remove all sdkperf tasks
      become: true
      command: pkill --signal 2 -f sdkperf
      ignore_errors: true

    - pause:
        seconds: 3
        prompt: "Waiting 3 seconds ...."
   
    - name: run sdkperf consuming 1 - topics_consumer_group_1
      shell: nohup taskset -c 0 {{sdkperf_nodes.sdkperf_root}}/sdkperf-c-x64/sdkperf_c -log=info -logf="{{sdkperf_nodes.sdkperf_log_root}}/bootstrap-debug-0.log" -epl="{{ sdkperf.epl }}" -rc="{{ sdkperf.rc }}" -nagle -cip="{{ sdkperf.broker_uri }}":"{{ sdkperf.broker_port }}" -cu="{{ sdkperf.client_consumer_username }}"@"{{ sdkperf.broker_msg_vpn }}" -cp="{{ sdkperf.client_consumer_password }}" -stl="{{ sdkperf.topics_consumer_group_1 }}" -pea=0 </dev/null > {{sdkperf_nodes.sdkperf_log_root}}/bootstrap-{{sdkperf.consumer_log_filename}}-0.log 2>&1 &

    - pause:
        seconds: 10
        prompt: "Waiting 3 seconds ...."

    - name: run sdkperf consuming 1 - topics_consumer_group_2
      shell: nohup taskset -c 1 {{sdkperf_nodes.sdkperf_root}}/sdkperf-c-x64/sdkperf_c -log=info -logf="{{sdkperf_nodes.sdkperf_log_root}}/bootstrap-debug-1.log" -epl="{{ sdkperf.epl }}" -rc="{{ sdkperf.rc }}" -nagle -cip="{{ sdkperf.broker_uri }}":"{{ sdkperf.broker_port }}" -cu="{{ sdkperf.client_consumer_username }}"@"{{ sdkperf.broker_msg_vpn }}" -cp="{{ sdkperf.client_consumer_password }}" -stl="{{ sdkperf.topics_consumer_group_1 }}" -pea=0 </dev/null > {{sdkperf_nodes.sdkperf_log_root}}/bootstrap-{{sdkperf.consumer_log_filename}}-1.log 2>&1 &

    - pause:
        seconds: 10
        prompt: "Waiting 10 seconds before stopping consumer"

    - name: remove all sdkperf tasks
      become: true
      command: pkill --signal 2 -f sdkperf
      ignore_errors: true


###
# The End.
