# ---------------------------------------------------------------------------------------------
# MIT License
# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke (ricardo.gomez-ulmke@solace.com)
# ---------------------------------------------------------------------------------------------

---
- name: "SDKPerf Latency to broker node"
  hosts: sdkperf_latency
  vars_files:
    - "../vars/bootstrap.vars.yml"
    - "../vars/sdkperf.vars.yml"
    - "./vars/monitor.vars.yml"

  tasks:

    - set_fact:
        # run_timestamp: "{{now(True)}}"
        result_dir: "{{ RESULT_DIR }}"

    - name: "Ensure ./tmp/latency exists"
      local_action:
        module: file
        path: "./tmp/latency"
        state: directory

    - name: "Ensure {{ result_dir }} exists"
      local_action:
        module: file
        path: "{{result_dir}}"
        state: directory

    - name: kicking of playbook
      debug:
        msg: "kicking of playbook"

    - name: Invoking repeating tasks
      include_tasks: ./tasks/sdkperf.latency.testrun.yml
      with_sequence: "end={{general.count}} start=0"


###
# The End.
