# ---------------------------------------------------------------------------------------------
# MIT License
# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke (ricardo.gomez-ulmke@solace.com)
# ---------------------------------------------------------------------------------------------

---

- hosts: broker_centos
  vars_files:
    - "../vars/bootstrap.vars.yml"
    - "../vars/sdkperf.vars.yml"
    - "./vars/monitor.vars.yml"

  tasks:

    - set_fact:
        result_dir: "{{ RESULT_DIR }}"
        run_id: "{{ RUN_ID }}"

    - name: kicking of playbook
      debug:
        msg: "kicking of playbook"

    - name: Invoking repeating tasks
      include_tasks: ./tasks/sdkperf.latency.brokernode.testrun.yml
      with_sequence: "end={{general.count}} start=0"


###
# The End.
