# ---------------------------------------------------------------------------------------------
# MIT License
# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke (ricardo.gomez-ulmke@solace.com)
# ---------------------------------------------------------------------------------------------

---
- hosts: sdkperf_latency
  tasks:
    - name: remove all sdkperf tasks
      become: true
      command: pkill --signal 2 -f sdkperf
      ignore_errors: true
