# ---------------------------------------------------------------------------------------------
# MIT License
# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke (ricardo.gomez-ulmke@solace.com)
# ---------------------------------------------------------------------------------------------

---

- name: "Ping broker node ..."
  shell: "ping -c {{ping.msg_number}} -q {{broker_pubsub.private_ip_address}} > {{sdkperf_nodes.sdkperf_log_root}}/{{sdkperf.ping_log_filename}}"

- name: download ping log file
  become: true
  fetch:
    src: "{{sdkperf_nodes.sdkperf_log_root}}/{{sdkperf.ping_log_filename}}"
    dest: "{{ result_dir }}/ping-stats.{{now(True)}}.log"
    flat: yes

- name: delete ping log file
  become: true
  file:
    path: "{{sdkperf_nodes.sdkperf_log_root}}/{{sdkperf.ping_log_filename}}"
    state: absent
