# ---------------------------------------------------------------------------------------------
# MIT License
# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke (ricardo.gomez-ulmke@solace.com)
# ---------------------------------------------------------------------------------------------

---
- name: remove all sdkperf tasks
  become: true
  command: pkill --signal 2 -f sdkperf
  ignore_errors: true

- pause:
    seconds: 3
    prompt: "Waiting 3 seconds ...."

- name: run sdkperf latency test
  shell: nohup taskset -c 1,2 {{sdkperf_nodes.sdkperf_root}}/sdkperf-c-x64/sdkperf_c -cip="{{ sdkperf.broker_uri }}":"{{ sdkperf.broker_port }}" -cu="{{ sdkperf.client_publisher_username }}"@"{{ sdkperf.broker_msg_vpn }}" -cp="{{ sdkperf.client_publisher_password }}" -ptl="{{ sdkperf.topics_latency }}" -stl="{{ sdkperf.topics_latency }}" -mn="{{ sdkperf.latency_msg_number }}" -msa="{{ sdkperf.latency_msg_payload_size_bytes }}" -mr="{{ sdkperf.latency_msg_rate_per_second }}" -psm -lat -lwu=10 -lb=4096 -lg=15 -l </dev/null > {{sdkperf_nodes.sdkperf_log_root}}/{{sdkperf.latency_repeat_filename}} 2>&1 &

- name: waiting for sdkperf to collect latency stats
  pause:
    seconds: "{{latency.repeat_single_test_run_duration_sec}}"

- name: remove sdkperf tasks
  become: true
  # killing sdkperf with signal 2 triggers flusing stats to logfile before dying
  command: pkill --signal 2 -f sdkperf
  ignore_errors: true

- name: download latency log file
  become: true
  fetch:
    src: "{{sdkperf_nodes.sdkperf_log_root}}/{{sdkperf.latency_repeat_filename}}"
    # dest: "{{sdkperf.latency_repeat_logs_download_folder}}"
    dest: "{{ result_dir }}/latency-stats.{{now(True)}}.log"
    # dest: "{{ result_dir }}/vpn-stats.{{now(True)}}.json"
    flat: yes
  vars:
    testrun_logfile_name: "latency-run.log"

- name: delete log file
  become: true
  file:
    path: "{{sdkperf_nodes.sdkperf_log_root}}/{{sdkperf.latency_repeat_filename}}"
    state: absent
