# ---------------------------------------------------------------------------------------------
# MIT License
# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke (ricardo.gomez-ulmke@solace.com)
# ---------------------------------------------------------------------------------------------

---

- name: "SDKPerf Latency: broker node to broker node"
  hosts: broker_centos
  vars_files:
    - "../vars/bootstrap.vars.yml"
    - "../vars/sdkperf.vars.yml"
    - "./vars/monitor.vars.yml"

  tasks:

    - set_fact:
        result_dir: "{{ RESULT_DIR }}"
        run_id: "{{ RUN_ID }}"
        log_tmp_dir: "./tmp/broker_node_latency"

    - name: "Ensure {{log_tmp_dir}} exists"
      local_action:
        module: file
        path: "{{log_tmp_dir}}"
        state: directory

    - name: "Ensure {{ result_dir }} exists"
      local_action:
        module: file
        path: "{{result_dir}}"
        state: directory

    - name: kicking of playbook
      debug:
        msg: "kicking of playbook"

    - name: Invoking repeating tasks
      include_tasks: ./tasks/sdkperf.latency.brokernode.testrun.yml
      with_sequence: "end={{general.count}} start=0"


###
# The End.
